apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-frontend-dev-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-frontend-dev-app
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-frontend-dev-app
    spec:
      containers:
        - name: torchlite-frontend-dev
          image: ghcr.io/htrc/torchlite-frontend:error-messages-2726ca4
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: dev
            - name: NODE_ENV
              value: development
            - name: KEYCLOAK_ISSUER_BASE_URL
              value: https://idp.dev.htrc.indiana.edu/realms/10000102
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: torchlite-frontend-secrets-dev
                  key: torchlite-client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: torchlite-frontend-secrets-dev
                  key: torchlite-client-secret
            - name: NEXTAUTH_URL
              value: https://torchlite-dev.htrc.illinois.edu
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: torchlite-frontend-secrets-dev
                  key: nextauth-secret
            - name: NEXT_PUBLIC_BASE_API_URI
              value: https://torchlite-dev-api.htrc.illinois.edu
            - name: REDIS_HOST
              value: redis-master.torchlite-dev.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: torchlite-frontend-secrets-dev
                  key: redis-password
      imagePullSecrets:
        - name: dockerconfigjson-github-com
