apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # 2 times the size of the stage mongodb persistent volume as we will be retaining the most recent 2 backups in the backup volume
