apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-stage-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-stage-app
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-stage-app
    spec:
      containers:
        - name: torchlite-backend-stage
          image: ghcr.io/htrc/torchlite-backend:develop
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: stage
            - name: KEYCLOAK_REALM
              value: https://idp.192.17.61.53.sslip.io/realms/htrc
            - name: TORCHLITE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-torchlite-client
                  key: torchlite-client-id
            - name: TORCHLITE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-torchlite-client
                  key: torchlite-client-secret
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas
                  key: atlas-url
            - name: AUTH_LEEWAY_SECONDS
              value: "60"
            - name: FEATURED_WORKSETS_URL
              value: https://raw.githubusercontent.com/htrc/torchlite-argocd/main/torchlite-backend/stage/config/config.yaml
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
