apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-stage-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-stage-app
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-stage-app
    spec:
      containers:
        - name: torchlite-backend-stage
          image: ghcr.io/htrc/torchlite-backend:stage-84addbc
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: stage
            - name: KEYCLOAK_REALM
              value: https://idp.stage.htrc.indiana.edu/realms/10000202
            - name: TORCHLITE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-stage
                  key: torchlite-client-id
            - name: TORCHLITE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-stage
                  key: torchlite-client-secret
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-stage
                  key: mongo-url
            - name: EF_API_URL
              value: http://torchlite-efapi-stage-service.torchlite-stage.svc.cluster.local:9000
            - name: AUTH_LEEWAY_SECONDS
              value: "60"
            - name: FEATURED_WORKSETS_URL
              value: https://raw.githubusercontent.com/htrc/torchlite-argocd/main/torchlite-backend/stage/config/config.yaml
            - name: FEATURED_WORKSET_USER
              value: e0ae4638-53f3-400e-8d74-4ebbefe532ad
            - name: REGISTRY_API_URL
              value: https://analytics.dev.htrc.indiana.edu
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
