apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htrc-ef-api-prod-argocd-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: torchlite
    notifications.argoproj.io/subscribe.on-health-degraded.slack: torchlite
spec:
  project: default

  source:
    repoURL: https://github.com/htrc/torchlite-argocd.git
    targetRevision: main
    path: htrc-ef-api/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: torchlite-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
