apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torchlite-backend-test-argocd-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: torchlite
    notifications.argoproj.io/subscribe.on-health-degraded.slack: torchlite
spec:
  project: default

  source:
    repoURL: https://github.com/htrc/torchlite-argocd.git
    targetRevision: HEAD
    path: torchlite-backend/test
  destination: 
    server: https://kubernetes.default.svc
    namespace: torchlite-test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
