apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torchlite-mongodb-sharded
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: torchlite
    notifications.argoproj.io/subscribe.on-health-degraded.slack: torchlite
spec:
  project: default

  sources:
    - repoURL: https://github.com/htrc/torchlite-argocd.git
      targetRevision: main
      ref: values
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: mongodb-sharded
      targetRevision: 8.0.7
      helm:
        releaseName: torchlite
        valueFiles:
          - $values/mongodb-sharded/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
