apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    meta.helm.sh/release-name: torchlite
    meta.helm.sh/release-namespace: mongodb
  creationTimestamp: "2024-05-13T21:33:00Z"
  generation: 6
  labels:
    app.kubernetes.io/component: mongos
    app.kubernetes.io/instance: torchlite
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb-sharded
    app.kubernetes.io/version: 7.0.9
    helm.sh/chart: mongodb-sharded-8.0.7
  name: torchlite-mongodb-sharded-mongos
  namespace: mongodb
  resourceVersion: "426898123"
  uid: 4bb5ff1b-32be-4337-8272-2bce3497fe49
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongos
      app.kubernetes.io/instance: torchlite
      app.kubernetes.io/name: mongodb-sharded
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-09-25T15:26:03-04:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: mongos
        app.kubernetes.io/instance: torchlite
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb-sharded
        app.kubernetes.io/version: 7.0.9
        helm.sh/chart: mongodb-sharded-8.0.7
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: mongos
                  app.kubernetes.io/instance: torchlite
                  app.kubernetes.io/name: mongodb-sharded
              topologyKey: kubernetes.io/hostname
            weight: 1
      automountServiceAccountToken: false
      containers:
      - env:
        - name: MONGODB_ENABLE_NUMACTL
          value: "no"
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MONGODB_SHARDING_MODE
          value: mongos
        - name: MONGODB_INIT_RETRY_ATTEMPTS
          value: "24"
        - name: MONGODB_INIT_RETRY_DELAY
          value: "5"
        - name: MONGODB_ROOT_USER
          value: root
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: torchlite-mongodb-sharded
        - name: MONGODB_REPLICA_SET_KEY
          valueFrom:
            secretKeyRef:
              key: mongodb-replica-set-key
              name: torchlite-mongodb-sharded
        - name: MONGODB_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: $(MONGODB_POD_NAME)
        - name: MONGODB_PORT_NUMBER
          value: "27017"
        - name: MONGODB_CFG_PRIMARY_HOST
          value: torchlite-mongodb-sharded-configsvr-0.torchlite-mongodb-sharded-headless.mongodb.svc.cluster.local
        - name: MONGODB_CFG_REPLICA_SET_NAME
          value: torchlite-mongodb-sharded-configsvr
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        image: docker.io/bitnami/mongodb-sharded:7.0.9-debian-12-r0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mongosh --port $MONGODB_PORT_NUMBER --eval "db.adminCommand('ping')"
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        name: mongos
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mongosh --port $MONGODB_PORT_NUMBER --eval "db.adminCommand('ping')"
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 20
        resources:
          limits:
            cpu: "6"
            ephemeral-storage: 10Gi
            memory: 12Gi
          requests:
            cpu: 1500m
            ephemeral-storage: 50Mi
            memory: 4Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /opt/bitnami/mongodb/conf
          name: empty-dir
          subPath: app-conf-dir
        - mountPath: /opt/bitnami/mongodb/tmp
          name: empty-dir
          subPath: app-tmp-dir
        - mountPath: /opt/bitnami/mongodb/logs
          name: empty-dir
          subPath: app-logs-dir
        - mountPath: /.mongodb
          name: empty-dir
          subPath: app-mongosh-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
      serviceAccount: torchlite-mongodb-sharded-mongos
      serviceAccountName: torchlite-mongodb-sharded-mongos
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: empty-dir
status:
  conditions:
  - lastTransitionTime: "2025-09-24T14:04:01Z"
    lastUpdateTime: "2025-09-24T14:04:01Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-09-25T19:36:05Z"
    lastUpdateTime: "2025-09-25T19:36:05Z"
    message: ReplicaSet "torchlite-mongodb-sharded-mongos-899b6fb97" has timed out
      progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 6
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1