apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torchlite-backend-prod-argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/htrc/torchlite-argocd.git
    targetRevision: HEAD
    path: torchlite-backend/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: torchlite-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
