apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torchlite-backend-dev-argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/htrc/torchlite-argocd.git
    targetRevision: HEAD
    path: torchlite-backend/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: torchlite-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
