featured_worksets:
  - name: Comparative Literature Workset
    id: 6408a63a30000067055ce2e9
    numVolumes: 927
    description:
             A list of works authored by non-Native Americans
             in HathiTrust on the similar subjects as the
             Native-authored workset during similar time
             period with similar language representation
    author: SCWAReD
    isPublic: true

  - name: The Black Fantastic Workset
    id: 642720e53300008d02a5dc9c
    numVolumes: 90
    description:
             90 volumes, including duplicates, of Black Fantastic
             fiction, identified by Dr. Seretha Williams and
             Dr. Clarissa West-White, as part of HTRC\'s SCWAReD
             project
    author: SCWAReD
    isPublic: true

  - name: History of Black Writers Workset
    id: 6407a1ec300000a4045ce2e7
    numVolumes: 2166
    description:
             Volumes found in HathiTrust written by African-American
             authors, as identified by the University of Kansas\'s
             Project on the History of Black Writing, released as part
             of the SCWAReD project
    author: SCWAReD
    isPublic: true

  - name: History of Black Writers Workset Sample
    id: 640ba4bf300000440a5ce31a
    numVolumes: 25
    description:
             25 volume sample of volumes found in HathiTrust written
             by African-American authors, as identified by the
             University of Kansas\'s Project on the History of Black
             Writing, released as part of the SCWAReD project
    author: SCWAReD
    isPublic: true
