apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-backup-prod-pv
spec:
  capacity:
    storage: 700Gi # 7 times the size of the prod mongodb persistent volume as we will be retaining 7 days of backups in the backup volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mongodb-backup
    type: DirectoryOrCreate
