apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-prod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Gi # 7 times the size of the prod mongodb persistent volume as we will be retaining 7 days of backups in the backup volume
