apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-dev-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: mongodb-backup-dev-pv
