apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-dev-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-dev-app
  replicas: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-dev-app
    spec:
      containers:
        - name: torchlite-backend-dev
          image: ghcr.io/htrc/torchlite-backend:develop-0cdfe98
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: dev
            - name: TORCHLITE_CONFIG
              value: https://raw.githubusercontent.com/htrc/torchlite-argocd/main/torchlite-backend/dev/config/config.yaml
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
