apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-dev-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-dev-app
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-dev-app
    spec:
      containers:
        - name: torchlite-backend-dev
          image: ghcr.io/htrc/torchlite-backend:develop-99abc35
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: dev
            - name: KEYCLOAK_REALM
              value: https://idp.dev.htrc.indiana.edu/realms/10000102
            - name: TORCHLITE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-dev
                  key: torchlite-client-id
            - name: TORCHLITE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-dev
                  key: torchlite-client-secret
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-dev
                  key: mongo-url
            - name: EF_API_URL
              value: https://data.htrc.illinois.edu/ef-api
            - name: AUTH_LEEWAY_SECONDS
              value: "60"
            - name: FEATURED_WORKSETS_URL
              value: https://raw.githubusercontent.com/htrc/torchlite-argocd/main/torchlite-backend/dev/config/config.yaml
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
