apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-dev-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-dev-app
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-dev-app
    spec:
      volumes:
        - name: registry-cert
          secret:
            secretName: registryapi-dev-cert
            items:
              - key: tls.crt
                path: crt
              - key: tls.key
                path: key
      containers:
        - name: torchlite-backend-dev
          image: ghcr.io/htrc/torchlite-backend:main-d65649e
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: registry-cert
              mountPath: "/etc/credentials"
              readOnly: true
          env:
            - name: ENV
              value: dev
            - name: KEYCLOAK_REALM
              value: https://idp.dev.htrc.indiana.edu/realms/10000102
            - name: TORCHLITE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-dev
                  key: torchlite-client-id
            - name: TORCHLITE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-dev
                  key: torchlite-client-secret
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: torchlite-backend-secrets-dev
                  key: mongo-url
            - name: EF_API_URL
              value: https://data.htrc.illinois.edu/ef-api
            - name: AUTH_LEEWAY_SECONDS
              value: "60"
            - name: FEATURED_WORKSETS_URL
              value: https://raw.githubusercontent.com/htrc/torchlite-argocd/main/torchlite-backend/dev/config/config.yaml
            - name: FEATURED_WORKSET_USER
              value: e0ae4638-53f3-400e-8d74-4ebbefe532ad
            - name: REGISTRY_API_URL
              value: https://registryapi.dev.htrc.indiana.edu
            - name: REGISTRY_TLS_CERT_PATH
              value: /etc/credentials/crt
            - name: REGISTRY_TLS_KEY_PATH
              value: /etc/credentials/key
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: torchlite-frontend-secrets-dev
                  key: redis-password
            - name: REDIS_HOST
              value: redis-master.torchlite-dev.svc.cluster.local
            - name: ENABLE_CACHE
              value: "true"
            - name: CACHE_EXPIRE
              value: "3600"
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
