apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-dev-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-dev-app
  replicas: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-dev-app
    spec:
      containers:
        - name: torchlite-backend-dev
          image: ghcr.io/htrc/torchlite-backend:develop-e7f686d
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: dev
      imagePullSecrets:
        - name: dockerconfigjson-github-com
