apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torchlite-backend-dev-ingress
  annotations:
    #kubernetes.io/ingress.class: public
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: buypass
spec:
  rules:
    - host: api.torchlite.192.17.61.53.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: torchlite-backend-dev-service
                port:
                  number: 8000
  tls:
    - hosts:
      - api.torchlite.192.17.61.53.nip.io
      secretName: torchlite-backend-dev-ingress-cert
