apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torchlite-backend-dev-ingress
  annotations:
    #kubernetes.io/ingress.class: public
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: buypass
    # nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    # nginx.ingress.kubernetes.io/cors-allow-methods: "OPTIONS, GET, PUT, POST"
    # nginx.ingress.kubernetes.io/cors-allow-origin: "https://torchlite-dev.192.17.61.53.nip.io, https://torchlite-*.vercel.app, http://localhost:8081"
    # nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    # nginx.ingress.kubernetes.io/cors-expose-headers: X-Torchlite-Version
    # nginx.ingress.kubernetes.io/cors-max-age: "86400"
    # nginx.ingress.kubernetes.io/enable-cors: "true"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin ~* (^https?://(torchlite-dev\.192\.17\.61\.53\.nip\.io|torchlite-[^.]+\.vercel\.app|localhost(:\d{2,5})))) {
          set $cors "true";
      }
      # Nginx doesn't support nested If statements. This is where things get slightly nasty.
      # Determine the HTTP request method used
      if ($request_method = 'OPTIONS') {
          set $cors "${cors}options";
      }
      if ($request_method = 'GET') {
          set $cors "${cors}get";
      }
      if ($request_method = 'POST') {
          set $cors "${cors}post";
      }

      if ($cors = "true") {
          # Catch all in case there's a request method we're not dealing with properly
          add_header 'Access-Control-Allow-Origin' "$http_origin";
      }

      if ($cors = "trueget") {
          add_header 'Access-Control-Allow-Origin' "$http_origin";
          add_header 'Access-Control-Allow-Credentials' 'true';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
          add_header 'Access-Control-Expose-Headers' 'X-Torchlite-Version'
      }

      if ($cors = "trueoptions") {
          add_header 'Access-Control-Allow-Origin' "$http_origin";

          #
          # Om nom nom cookies
          #
          add_header 'Access-Control-Allow-Credentials' 'true';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';

          #
          # Custom headers and headers various browsers *should* be OK with but aren't
          #
          add_header 'Access-Control-Allow-Headers' 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

          #
          # Tell client that this pre-flight info is valid for 20 days
          #
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain charset=UTF-8';
          add_header 'Content-Length' 0;
          return 204;
      }

      if ($cors = "truepost") {
          add_header 'Access-Control-Allow-Origin' "$http_origin";
          add_header 'Access-Control-Allow-Credentials' 'true';
          add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
          add_header 'Access-Control-Expose-Headers' 'X-Torchlite-Version'
      }

spec:
  rules:
    - host: torchlite-dev-api.192.17.61.53.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: torchlite-backend-dev-service
                port:
                  number: 8000
  tls:
    - hosts:
      - torchlite-dev-api.192.17.61.53.nip.io
      secretName: torchlite-backend-dev-ingress-cert
