apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-frontend-prod-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-frontend-prod-app
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-frontend-prod-app
    spec:
      containers:
        - name: torchlite-frontend-prod
          image: ghcr.io/htrc/torchlite-frontend:google-analytics-fc6df4d
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: prod
            - name: NODE_ENV
              value: production
            - name: KEYCLOAK_ISSUER_BASE_URL
              value: https://login.analytics.hathitrust.org/realms/10000202
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-torchlite-client
                  key: torchlite-client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-torchlite-client
                  key: torchlite-client-secret
            - name: NEXTAUTH_URL
              value: https://torchlite.htrc.illinois.edu
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextauth
                  key: nextauth-secret
            - name: NEXT_PUBLIC_BASE_API_URI
              value: https://torchlite-api.htrc.illinois.edu
            - name: REDIS_HOST
              value: redis-master.torchlite-prod.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: GOOGLE_ANALYTICS_ID
              value: "G-XPLYSCJRWG"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
