apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-frontend-prod-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-frontend-prod-app
  replicas: 1
  template:
    metadata:
      labels:
        app: torchlite-frontend-prod-app
    spec:
      containers:
        - name: torchlite-frontend-prod
          image: ghcr.io/htrc/torchlite-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: prod
            - name: NODE_ENV
              value: production
            - name: JWT_TIMEOUT
              value: '86400'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: NEXTAUTH_URL
              value: https://torchlite.htrc.illinois.edu
            - name: NEXTAUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nextauth-secret-key
                  key: nextauth-secret-key
            - name: NEXT_PUBLIC_BASE_API_URI
              value: https://torchlite-api.htrc.illinois.edu
      imagePullSecrets:
        - name: dockerconfigjson-github-com
