apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-prod-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-prod-app
  replicas: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-prod-app
    spec:
      containers:
        - name: torchlite-backend-prod-app
          image: ghcr.io/htrc/torchlite-backend:github-actions
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: prod
      imagePullSecrets:
        - name: dockerconfigjson-github-com
