apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchlite-backend-prod-deployment
spec:
  selector:
    matchLabels:
      app: torchlite-backend-prod-app
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: torchlite-backend-prod-app
    spec:
      volumes:
        - name: registry-cert
          secret:
            secretName: registryapi-prod-cert
            items:
              - key: tls.crt
                path: crt
              - key: tls.key
                path: key
      containers:
        - name: torchlite-backend-prod-app
          image: ghcr.io/htrc/torchlite-backend:main-17cc90c
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: registry-cert
              mountPath: "/etc/credentials"
              readOnly: true
          env:
            - name: ENV
              value: prod
            - name: KEYCLOAK_REALM
              value: https://login.analytics.hathitrust.org/realms/10000202
            - name: TORCHLITE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-torchlite-client
                  key: torchlite-client-id
            - name: TORCHLITE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-torchlite-client
                  key: torchlite-client-secret
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: torchlite-mongo
                  key: torchlite-mongo-url
            - name: EF_API_URL
              value: http://torchlite-efapi-prod-service.torchlite-prod.svc.cluster.local:9000
            - name: AUTH_LEEWAY_SECONDS
              value: "60"
            - name: FEATURED_WORKSETS_URL
              value: https://raw.githubusercontent.com/htrc/torchlite-argocd/main/torchlite-backend/prod/config/config.yaml
            - name: FEATURED_WORKSET_USER
              value: e0ae4638-53f3-400e-8d74-4ebbefe532ad
            - name: REGISTRY_API_URL
              value: https://registryapi.internal.htrc.indiana.edu
            - name: REGISTRY_TLS_CERT_PATH
              value: /etc/credentials/crt
            - name: REGISTRY_TLS_KEY_PATH
              value: /etc/credentials/key
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_HOST
              value: redis-master.torchlite-prod.svc.cluster.local
            - name: ENABLE_CACHE
              value: "true"
            - name: CACHE_EXPIRE
              value: "300"
            - name: GOOGLE_ANALYTICS_ID
              value: "G-XPLYSCJRWG"
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 20
      imagePullSecrets:
        - name: dockerconfigjson-github-com
