apiVersion: apps/v1
kind: Deployment
metadata:
  name: ef-api-dev-deployment
spec:
  selector:
    matchLabels:
      app: ef-api-dev-app
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ef-api-dev-app
    spec:
      containers:
        - name: ef-api-dev
          image: ghcr.io/htrc/htrc-ef-api:develop
          ports:
            - containerPort: 9000
          env:
            - name: ENV
              value: dev
            - name: EFAPI_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ef-api-secrets
                  key: mongo-url
            - name: EFAPI_SECRET
              valueFrom:
                secretKeyRef:
                  name: ef-api-secrets
                  key: secret-key
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
      imagePullSecrets:
        - name: dockerconfigjson-github-com
